import json
from pathlib import Path

import pytest

from xscraper.token import js_float_to_radix, syndication_token

# Pairs generated by running the embed widget's formula in Node (V8).
V8_TOKENS = json.loads((Path(__file__).parent / "fixtures" / "v8_tokens.json").read_text())


@pytest.mark.parametrize("tweet_id,expected", V8_TOKENS)
def test_matches_v8(tweet_id, expected):
    assert syndication_token(tweet_id) == expected


@pytest.mark.parametrize("value,expected", [
    (0.0, "0"), (35.0, "z"), (36.0, "10"), (-255.5, "-73.i"), (0.5, "0.i"),
    (float("inf"), "Infinity"), (float("nan"), "NaN"),
])
def test_js_float_to_radix(value, expected):
    assert js_float_to_radix(value, 36) == expected


def test_accepts_int_and_str():
    assert syndication_token(20) == syndication_token("20") == "6dq1a2xwd93"
