"""Sentiment tables shared with wasm-core/src/lib.rs (must stay identical)."""

LEXICON: dict[str, int] = {
    "abandon": -2,
    "abuse": -3,
    "accomplished": 2,
    "amazing": 4,
    "angry": -3,
    "annoying": -2,
    "anxious": -2,
    "appreciate": 2,
    "awesome": 4,
    "awful": -3,
    "bad": -3,
    "beautiful": 3,
    "best": 3,
    "better": 2,
    "bless": 2,
    "boring": -3,
    "brilliant": 4,
    "broken": -1,
    "bug": -2,
    "bullish": 2,
    "bearish": -2,
    "calm": 2,
    "celebrate": 3,
    "cheer": 2,
    "confused": -2,
    "congrats": 2,
    "congratulations": 2,
    "cool": 1,
    "crash": -2,
    "crisis": -3,
    "cry": -1,
    "damn": -2,
    "dead": -3,
    "delighted": 3,
    "disappointed": -2,
    "disaster": -2,
    "disgusting": -3,
    "dumb": -3,
    "easy": 1,
    "enjoy": 2,
    "error": -2,
    "excellent": 3,
    "excited": 3,
    "fail": -2,
    "failed": -2,
    "failure": -2,
    "fake": -3,
    "fantastic": 4,
    "fear": -2,
    "fine": 2,
    "fix": 1,
    "fixed": 2,
    "fraud": -4,
    "free": 1,
    "fun": 4,
    "glad": 3,
    "good": 3,
    "gorgeous": 3,
    "great": 3,
    "grateful": 3,
    "happy": 3,
    "hate": -3,
    "hope": 2,
    "horrible": -3,
    "hurt": -2,
    "impressive": 3,
    "incredible": 4,
    "innovative": 2,
    "inspiring": 3,
    "interesting": 2,
    "kill": -3,
    "lame": -2,
    "launch": 1,
    "lol": 3,
    "lose": -3,
    "loss": -3,
    "love": 3,
    "loved": 3,
    "lovely": 3,
    "mad": -3,
    "mess": -2,
    "nice": 3,
    "outage": -2,
    "pain": -2,
    "perfect": 3,
    "pleased": 3,
    "poor": -2,
    "problem": -2,
    "proud": 2,
    "rage": -2,
    "recommend": 2,
    "sad": -2,
    "scam": -2,
    "scary": -2,
    "shame": -2,
    "sick": -2,
    "slow": -2,
    "sorry": -1,
    "stupid": -2,
    "success": 2,
    "successful": 3,
    "super": 3,
    "terrible": -3,
    "thank": 2,
    "thanks": 2,
    "thrilled": 5,
    "ugly": -3,
    "upset": -2,
    "useless": -2,
    "win": 4,
    "winning": 4,
    "wonderful": 4,
    "worried": -3,
    "worse": -3,
    "worst": -3,
    "wow": 4,
    "wrong": -2,
    "yay": 2,
}

NEGATORS = frozenset({
    "ain't", 'aint', "can't", 'cannot', 'cant', "didn't", 'didnt', "doesn't", 'doesnt',
    "don't", 'dont', "isn't", 'isnt', 'neither', 'never', 'no', 'nobody', 'nor', 'not',
    'nothing', "wasn't", 'wasnt', 'without', "won't", 'wont',
})

BOOSTERS = frozenset({
    'absolutely', 'extremely', 'incredibly', 'really', 'so', 'super', 'totally', 'very',
})
