"""Generate the word-character table shared by the Rust core and the Python engine.

A "word character" (for hashtags and tokenisation) is any code point whose
general category is a Letter (L*), Number (N*) or Mark (M*), matching X's
hashtag rules. Marks matter: without them Devanagari, Tamil, Thai and other
scripts' hashtags are cut off at the first vowel sign.

Both engines read the same generated ranges, so their results agree whatever
Unicode version the local Python or Rust toolchain ships.

Usage: python3 scripts/gen_unicode_tables.py   (then scripts/build_wasm.sh)
"""
import sys
import textwrap
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def word_ranges():
    ranges = []
    for cp in range(0x80, sys.maxunicode + 1):
        if unicodedata.category(chr(cp))[0] in "LNM":
            if ranges and ranges[-1][1] == cp - 1:
                ranges[-1][1] = cp
            else:
                ranges.append([cp, cp])
    return ranges


def main():
    ranges = word_ranges()
    version = unicodedata.unidata_version
    header = f"Generated by scripts/gen_unicode_tables.py from Unicode {version}. Do not edit."

    rows = "\n".join(f"    (0x{a:X}, 0x{b:X})," for a, b in ranges)
    (ROOT / "wasm-core/src/unicode_tables.rs").write_text(
        f"// {header}\n\n"
        f"pub const UNICODE_VERSION: &str = \"{version}\";\n\n"
        "/// Inclusive ranges of non-ASCII letters, numbers and marks, sorted.\n"
        f"pub static WORD_RANGES: &[(u32, u32)] = &[\n{rows}\n];\n"
    )

    def wrap(values):
        return textwrap.fill(", ".join(f"0x{v:X}" for v in values) + ",", 96,
                             initial_indent="    ", subsequent_indent="    ")

    starts = wrap(a for a, _ in ranges)
    ends = wrap(b for _, b in ranges)
    (ROOT / "xscraper/analysis/_unicode_tables.py").write_text(
        f"# {header}\n# fmt: off\n\n"
        f"UNICODE_VERSION = \"{version}\"\n\n"
        "# Inclusive ranges of non-ASCII letters, numbers and marks, sorted.\n"
        f"WORD_STARTS = (\n{starts}\n)\n\n"
        f"WORD_ENDS = (\n{ends}\n)\n"
    )
    print(f"Unicode {version}: {len(ranges)} ranges")


if __name__ == "__main__":
    main()
